### ISSUE TITLE
Typing into the task list causes the task list to disappear on iOS

### ISSUE THREAD

**Issue by stubailo** [percolatestudio/mdg-todos#20] opened 2014-09-25 21:54 UTC
This might be a browser error, but it might be possible to fix somehow. Reproduction:
1. Launch the app in the iOS simulator or an iPhone running iOS 8.
2. Tap one of the tasks
3. Type some text
4. The whole task list disappears in some sort of weird rendering bug

Or:
1. Launch the app in the iOS simulator and in a browser
2. Open the same list in the simulator and the browset
3. Edit one of the tasks in the browser
4. The same glitch happens in the simulator where the task list becomes invisible

**Comment by tmeasday** [comment] 2014-09-26 01:24
Not seeing this in either the iOS8 simulator or on a physical phone (with either reproduction). Anyone else?

**Comment by domyen** [comment] 2014-09-26 20:47
Can't seem to get a repro on iphone5s ios8. Might be related to https://github.com/percolatestudio/mdg-todos/issues/27?

**Comment by stubailo** [comment] 2014-09-26 21:14
Weird, I can't reproduce it anymore - no idea what caused this when Matt and I experienced it.

**Comment by zol** [comment] 2014-09-29 20:21
Closing this due to lack of repro.

**Closed as completed by zol** 2014-09-29 20:21 UTC
Labels: bug
